name: machine_test
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^5.2.0
  http: ^0.13.6
  flutter_bloc: ^8.1.5
  get: ^4.6.6
  flutter_custom_clippers: ^2.1.0
  injectable: ^2.3.5
  get_it: ^7.6.7
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.8.1
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.3+1
  http_parser: ^4.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner:
  injectable_generator:
  json_serializable: ^6.8.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
